/**
 * Lista de países para el selector de dirección
 * ISO 3166-1, ordenados alfabéticamente en español
 */

export interface Country {
  code: string
  name: string
}

const COUNTRIES_RAW: Country[] = [
  { code: "AD", name: "Andorra" },
  { code: "AE", name: "Emiratos Árabes Unidos" },
  { code: "AF", name: "Afganistán" },
  { code: "AG", name: "Antigua y Barbuda" },
  { code: "AL", name: "Albania" },
  { code: "AM", name: "Armenia" },
  { code: "AR", name: "Argentina" },
  { code: "AT", name: "Austria" },
  { code: "AU", name: "Australia" },
  { code: "AZ", name: "Azerbaiyán" },
  { code: "BA", name: "Bosnia y Herzegovina" },
  { code: "BB", name: "Barbados" },
  { code: "BD", name: "Bangladesh" },
  { code: "BE", name: "Bélgica" },
  { code: "BG", name: "Bulgaria" },
  { code: "BH", name: "Baréin" },
  { code: "BN", name: "Brunei" },
  { code: "BO", name: "Bolivia" },
  { code: "BR", name: "Brasil" },
  { code: "BS", name: "Bahamas" },
  { code: "BT", name: "Bután" },
  { code: "BY", name: "Bielorrusia" },
  { code: "BZ", name: "Belice" },
  { code: "CA", name: "Canadá" },
  { code: "CH", name: "Suiza" },
  { code: "CL", name: "Chile" },
  { code: "CN", name: "China" },
  { code: "CO", name: "Colombia" },
  { code: "CR", name: "Costa Rica" },
  { code: "CY", name: "Chipre" },
  { code: "CZ", name: "República Checa" },
  { code: "DE", name: "Alemania" },
  { code: "DK", name: "Dinamarca" },
  { code: "DO", name: "República Dominicana" },
  { code: "DZ", name: "Argelia" },
  { code: "EC", name: "Ecuador" },
  { code: "EE", name: "Estonia" },
  { code: "EG", name: "Egipto" },
  { code: "ES", name: "España" },
  { code: "FI", name: "Finlandia" },
  { code: "FJ", name: "Fiyi" },
  { code: "FM", name: "Micronesia" },
  { code: "FR", name: "Francia" },
  { code: "GB", name: "Reino Unido" },
  { code: "GE", name: "Georgia" },
  { code: "GH", name: "Ghana" },
  { code: "GR", name: "Grecia" },
  { code: "GT", name: "Guatemala" },
  { code: "GY", name: "Guyana" },
  { code: "HK", name: "Hong Kong" },
  { code: "HN", name: "Honduras" },
  { code: "HR", name: "Croacia" },
  { code: "HU", name: "Hungría" },
  { code: "ID", name: "Indonesia" },
  { code: "IE", name: "Irlanda" },
  { code: "IL", name: "Israel" },
  { code: "IN", name: "India" },
  { code: "IQ", name: "Irak" },
  { code: "IR", name: "Irán" },
  { code: "IS", name: "Islandia" },
  { code: "IT", name: "Italia" },
  { code: "JM", name: "Jamaica" },
  { code: "JO", name: "Jordania" },
  { code: "JP", name: "Japón" },
  { code: "KE", name: "Kenia" },
  { code: "KH", name: "Camboya" },
  { code: "KN", name: "San Cristóbal y Nieves" },
  { code: "KR", name: "Corea del Sur" },
  { code: "KW", name: "Kuwait" },
  { code: "KZ", name: "Kazajistán" },
  { code: "LA", name: "Laos" },
  { code: "LB", name: "Líbano" },
  { code: "LC", name: "Santa Lucía" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LK", name: "Sri Lanka" },
  { code: "LT", name: "Lituania" },
  { code: "LU", name: "Luxemburgo" },
  { code: "LV", name: "Letonia" },
  { code: "MA", name: "Marruecos" },
  { code: "MC", name: "Mónaco" },
  { code: "MD", name: "Moldavia" },
  { code: "ME", name: "Montenegro" },
  { code: "MH", name: "Islas Marshall" },
  { code: "MK", name: "Macedonia del Norte" },
  { code: "MM", name: "Myanmar" },
  { code: "MN", name: "Mongolia" },
  { code: "MO", name: "Macao" },
  { code: "MT", name: "Malta" },
  { code: "MX", name: "México" },
  { code: "MY", name: "Malasia" },
  { code: "NG", name: "Nigeria" },
  { code: "NI", name: "Nicaragua" },
  { code: "NL", name: "Países Bajos" },
  { code: "NO", name: "Noruega" },
  { code: "NP", name: "Nepal" },
  { code: "NZ", name: "Nueva Zelanda" },
  { code: "OM", name: "Omán" },
  { code: "PA", name: "Panamá" },
  { code: "PE", name: "Perú" },
  { code: "PH", name: "Filipinas" },
  { code: "PK", name: "Pakistán" },
  { code: "PL", name: "Polonia" },
  { code: "PR", name: "Puerto Rico" },
  { code: "PS", name: "Palestina" },
  { code: "PT", name: "Portugal" },
  { code: "PY", name: "Paraguay" },
  { code: "QA", name: "Catar" },
  { code: "RO", name: "Rumania" },
  { code: "RS", name: "Serbia" },
  { code: "RU", name: "Rusia" },
  { code: "SA", name: "Arabia Saudí" },
  { code: "SE", name: "Suecia" },
  { code: "SG", name: "Singapur" },
  { code: "SI", name: "Eslovenia" },
  { code: "SK", name: "Eslovaquia" },
  { code: "SV", name: "El Salvador" },
  { code: "SY", name: "Siria" },
  { code: "TH", name: "Tailandia" },
  { code: "TN", name: "Túnez" },
  { code: "TR", name: "Turquía" },
  { code: "TT", name: "Trinidad y Tobago" },
  { code: "TW", name: "Taiwán" },
  { code: "UA", name: "Ucrania" },
  { code: "US", name: "Estados Unidos" },
  { code: "UY", name: "Uruguay" },
  { code: "UZ", name: "Uzbekistán" },
  { code: "VE", name: "Venezuela" },
  { code: "VN", name: "Vietnam" },
  { code: "ZA", name: "Sudáfrica" },
]

// Ordenar alfabéticamente y exportar sin duplicados
export const COUNTRIES = [...COUNTRIES_RAW].sort((a, b) =>
  a.name.localeCompare(b.name, "es")
)

export function getCountryName(code: string): string {
  const country = COUNTRIES.find((c) => c.code === code)
  return country?.name ?? code
}

export function getCountryCode(name: string): string {
  const country = COUNTRIES.find((c) => c.name === name)
  return country?.code ?? ""
}
