/**
 * Lista completa de países para el selector
 * Compatible con Stripe y envíos internacionales
 */

export interface Country {
  code: string;
  name: string;
}

export const COUNTRIES: Country[] = [
  { code: 'MX', name: 'México' },
  { code: 'US', name: 'Estados Unidos' },
  { code: 'CA', name: 'Canadá' },
  { code: 'AR', name: 'Argentina' },
  { code: 'BR', name: 'Brasil' },
  { code: 'CL', name: 'Chile' },
  { code: 'CO', name: 'Colombia' },
  { code: 'CR', name: 'Costa Rica' },
  { code: 'EC', name: 'Ecuador' },
  { code: 'ES', name: 'España' },
  { code: 'GT', name: 'Guatemala' },
  { code: 'HN', name: 'Honduras' },
  { code: 'NI', name: 'Nicaragua' },
  { code: 'PA', name: 'Panamá' },
  { code: 'PE', name: 'Perú' },
  { code: 'PR', name: 'Puerto Rico' },
  { code: 'DO', name: 'República Dominicana' },
  { code: 'UY', name: 'Uruguay' },
  { code: 'VE', name: 'Venezuela' },
  { code: 'GB', name: 'Reino Unido' },
  { code: 'FR', name: 'Francia' },
  { code: 'DE', name: 'Alemania' },
  { code: 'IT', name: 'Italia' },
  { code: 'PT', name: 'Portugal' },
  { code: 'AU', name: 'Australia' },
  { code: 'NZ', name: 'Nueva Zelanda' },
  { code: 'JP', name: 'Japón' },
  { code: 'CN', name: 'China' },
  { code: 'IN', name: 'India' },
  { code: 'KR', name: 'Corea del Sur' },
  { code: 'SG', name: 'Singapur' },
  { code: 'AE', name: 'Emiratos Árabes Unidos' },
  { code: 'SA', name: 'Arabia Saudí' },
  { code: 'IL', name: 'Israel' },
  { code: 'ZA', name: 'Sudáfrica' },
  { code: 'EG', name: 'Egipto' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'KE', name: 'Kenia' },
  { code: 'GH', name: 'Ghana' },
  { code: 'MA', name: 'Marruecos' },
  { code: 'DZ', name: 'Argelia' },
  { code: 'TN', name: 'Túnez' },
  { code: 'RU', name: 'Rusia' },
  { code: 'TR', name: 'Turquía' },
  { code: 'PL', name: 'Polonia' },
  { code: 'NL', name: 'Países Bajos' },
  { code: 'BE', name: 'Bélgica' },
  { code: 'CH', name: 'Suiza' },
  { code: 'AT', name: 'Austria' },
  { code: 'SE', name: 'Suecia' },
  { code: 'NO', name: 'Noruega' },
  { code: 'DK', name: 'Dinamarca' },
  { code: 'FI', name: 'Finlandia' },
  { code: 'IE', name: 'Irlanda' },
  { code: 'GR', name: 'Grecia' },
  { code: 'CZ', name: 'República Checa' },
  { code: 'HU', name: 'Hungría' },
  { code: 'RO', name: 'Rumania' },
  { code: 'BG', name: 'Bulgaria' },
  { code: 'HR', name: 'Croacia' },
  { code: 'SK', name: 'Eslovaquia' },
  { code: 'SI', name: 'Eslovenia' },
  { code: 'LT', name: 'Lituania' },
  { code: 'LV', name: 'Letonia' },
  { code: 'EE', name: 'Estonia' },
  { code: 'MT', name: 'Malta' },
  { code: 'CY', name: 'Chipre' },
  { code: 'LU', name: 'Luxemburgo' },
  { code: 'IS', name: 'Islandia' },
  { code: 'AD', name: 'Andorra' },
  { code: 'MC', name: 'Mónaco' },
  { code: 'SM', name: 'San Marino' },
  { code: 'VA', name: 'Ciudad del Vaticano' },
  { code: 'LI', name: 'Liechtenstein' },
  { code: 'PH', name: 'Filipinas' },
  { code: 'TH', name: 'Tailandia' },
  { code: 'VN', name: 'Vietnam' },
  { code: 'MY', name: 'Malasia' },
  { code: 'ID', name: 'Indonesia' },
  { code: 'BD', name: 'Bangladesh' },
  { code: 'PK', name: 'Pakistán' },
  { code: 'LK', name: 'Sri Lanka' },
  { code: 'MM', name: 'Myanmar' },
  { code: 'KH', name: 'Camboya' },
  { code: 'LA', name: 'Laos' },
  { code: 'BN', name: 'Brunei' },
  { code: 'TW', name: 'Taiwán' },
  { code: 'HK', name: 'Hong Kong' },
  { code: 'MO', name: 'Macao' },
  { code: 'MN', name: 'Mongolia' },
  { code: 'KZ', name: 'Kazajistán' },
  { code: 'UZ', name: 'Uzbekistán' },
  { code: 'GE', name: 'Georgia' },
  { code: 'AM', name: 'Armenia' },
  { code: 'AZ', name: 'Azerbaiyán' },
  { code: 'BY', name: 'Bielorrusia' },
  { code: 'UA', name: 'Ucrania' },
  { code: 'MD', name: 'Moldavia' },
  { code: 'RS', name: 'Serbia' },
  { code: 'BA', name: 'Bosnia y Herzegovina' },
  { code: 'MK', name: 'Macedonia del Norte' },
  { code: 'AL', name: 'Albania' },
  { code: 'ME', name: 'Montenegro' },
  { code: 'XK', name: 'Kosovo' },
  { code: 'BH', name: 'Baréin' },
  { code: 'KW', name: 'Kuwait' },
  { code: 'OM', name: 'Omán' },
  { code: 'QA', name: 'Catar' },
  { code: 'YE', name: 'Yemen' },
  { code: 'IQ', name: 'Irak' },
  { code: 'JO', name: 'Jordania' },
  { code: 'LB', name: 'Líbano' },
  { code: 'SY', name: 'Siria' },
  { code: 'PS', name: 'Palestina' },
  { code: 'IR', name: 'Irán' },
  { code: 'AF', name: 'Afganistán' },
  { code: 'NP', name: 'Nepal' },
  { code: 'BT', name: 'Bután' },
  { code: 'MV', name: 'Maldivas' },
  { code: 'FJ', name: 'Fiyi' },
  { code: 'PG', name: 'Papúa Nueva Guinea' },
  { code: 'SB', name: 'Islas Salomón' },
  { code: 'VU', name: 'Vanuatu' },
  { code: 'NC', name: 'Nueva Caledonia' },
  { code: 'PF', name: 'Polinesia Francesa' },
  { code: 'WS', name: 'Samoa' },
  { code: 'TO', name: 'Tonga' },
  { code: 'KI', name: 'Kiribati' },
  { code: 'TV', name: 'Tuvalu' },
  { code: 'NR', name: 'Nauru' },
  { code: 'PW', name: 'Palaos' },
  { code: 'FM', name: 'Micronesia' },
  { code: 'MH', name: 'Islas Marshall' },
  { code: 'BS', name: 'Bahamas' },
  { code: 'BB', name: 'Barbados' },
  { code: 'JM', name: 'Jamaica' },
  { code: 'TT', name: 'Trinidad y Tobago' },
  { code: 'GD', name: 'Granada' },
  { code: 'LC', name: 'Santa Lucía' },
  { code: 'VC', name: 'San Vicente y las Granadinas' },
  { code: 'AG', name: 'Antigua y Barbuda' },
  { code: 'DM', name: 'Dominica' },
  { code: 'KN', name: 'San Cristóbal y Nieves' },
  { code: 'BZ', name: 'Belice' },
  { code: 'SV', name: 'El Salvador' },
  { code: 'PY', name: 'Paraguay' },
  { code: 'BO', name: 'Bolivia' },
  { code: 'GY', name: 'Guyana' },
  { code: 'SR', name: 'Surinam' },
  { code: 'GF', name: 'Guayana Francesa' },
  { code: 'FK', name: 'Islas Malvinas' },
  { code: 'GS', name: 'Georgia del Sur e Islas Sandwich del Sur' },
  { code: 'TF', name: 'Territorios Australes Franceses' },
  { code: 'AQ', name: 'Antártida' },
  { code: 'GL', name: 'Groenlandia' },
  { code: 'FO', name: 'Islas Feroe' },
  { code: 'SJ', name: 'Svalbard y Jan Mayen' },
  { code: 'AX', name: 'Islas Åland' },
  { code: 'GI', name: 'Gibraltar' },
  { code: 'AD', name: 'Andorra' },
  { code: 'MC', name: 'Mónaco' },
  { code: 'SM', name: 'San Marino' },
  { code: 'VA', name: 'Ciudad del Vaticano' },
  { code: 'LI', name: 'Liechtenstein' },
  { code: 'MT', name: 'Malta' },
  { code: 'CY', name: 'Chipre' },
  { code: 'LU', name: 'Luxemburgo' },
  { code: 'IS', name: 'Islandia' },
  { code: 'IE', name: 'Irlanda' },
  { code: 'PT', name: 'Portugal' },
  { code: 'GR', name: 'Grecia' },
  { code: 'CZ', name: 'República Checa' },
  { code: 'HU', name: 'Hungría' },
  { code: 'RO', name: 'Rumania' },
  { code: 'BG', name: 'Bulgaria' },
  { code: 'HR', name: 'Croacia' },
  { code: 'SK', name: 'Eslovaquia' },
  { code: 'SI', name: 'Eslovenia' },
  { code: 'LT', name: 'Lituania' },
  { code: 'LV', name: 'Letonia' },
  { code: 'EE', name: 'Estonia' },
  { code: 'PL', name: 'Polonia' },
  { code: 'NL', name: 'Países Bajos' },
  { code: 'BE', name: 'Bélgica' },
  { code: 'CH', name: 'Suiza' },
  { code: 'AT', name: 'Austria' },
  { code: 'SE', name: 'Suecia' },
  { code: 'NO', name: 'Noruega' },
  { code: 'DK', name: 'Dinamarca' },
  { code: 'FI', name: 'Finlandia' },
  { code: 'DE', name: 'Alemania' },
  { code: 'IT', name: 'Italia' },
  { code: 'ES', name: 'España' },
  { code: 'FR', name: 'Francia' },
  { code: 'GB', name: 'Reino Unido' },
  { code: 'US', name: 'Estados Unidos' },
  { code: 'CA', name: 'Canadá' },
  { code: 'MX', name: 'México' },
  { code: 'AR', name: 'Argentina' },
  { code: 'BR', name: 'Brasil' },
  { code: 'CL', name: 'Chile' },
  { code: 'CO', name: 'Colombia' },
  { code: 'CR', name: 'Costa Rica' },
  { code: 'EC', name: 'Ecuador' },
  { code: 'GT', name: 'Guatemala' },
  { code: 'HN', name: 'Honduras' },
  { code: 'NI', name: 'Nicaragua' },
  { code: 'PA', name: 'Panamá' },
  { code: 'PE', name: 'Perú' },
  { code: 'PR', name: 'Puerto Rico' },
  { code: 'DO', name: 'República Dominicana' },
  { code: 'UY', name: 'Uruguay' },
  { code: 'VE', name: 'Venezuela' },
  { code: 'AU', name: 'Australia' },
  { code: 'NZ', name: 'Nueva Zelanda' },
  { code: 'JP', name: 'Japón' },
  { code: 'CN', name: 'China' },
  { code: 'IN', name: 'India' },
  { code: 'KR', name: 'Corea del Sur' },
  { code: 'SG', name: 'Singapur' },
  { code: 'AE', name: 'Emiratos Árabes Unidos' },
  { code: 'SA', name: 'Arabia Saudí' },
  { code: 'IL', name: 'Israel' },
  { code: 'ZA', name: 'Sudáfrica' },
  { code: 'EG', name: 'Egipto' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'KE', name: 'Kenia' },
  { code: 'GH', name: 'Ghana' },
  { code: 'MA', name: 'Marruecos' },
  { code: 'DZ', name: 'Argelia' },
  { code: 'TN', name: 'Túnez' },
  { code: 'RU', name: 'Rusia' },
  { code: 'TR', name: 'Turquía' },
];

// Ordenar países alfabéticamente por nombre
COUNTRIES.sort((a, b) => a.name.localeCompare(b.name, 'es'));

// Función helper para obtener el nombre del país por código
export function getCountryName(code: string): string {
  const country = COUNTRIES.find(c => c.code === code);
  return country?.name || code;
}

// Función helper para obtener el código del país por nombre
export function getCountryCode(name: string): string {
  const country = COUNTRIES.find(c => c.name === name);
  return country?.code || '';
}

